### ISSUE TITLE
Request task list / taskfolders / ...

### ISSUE THREAD

**Issue by rexyiy** [black-roland/homeassistant-microsoft-todo#11]
Hi,
today I tried messing around with you amzing code. I wanted to see if I can get a taskfolders list. My idea was to change the endpoint to the URI listed in the docs and remove the not needed subject etc:
```
def test(self, subject=None, list_id=None, note=None, due_date=None, reminder_date_time=None):
    uri = self.api_endpoint + "/beta/me/taskfolders"
        
    try:
        # self.logger.debug("Create task request: %s", task_req)
        res = self.client.post(uri)
        res.raise_for_status()
        self.logger.debug("Create task response: %s", res.json())
    except HTTPError as e:
        self.logger.error("Unable to create task: %s. Response: %s", e, res.json())

    return res
```
But sadly this didn't work. The server responded with this error:
`Write requests (excluding DELETE) must contain the Content-Type header declaration.`
I also tried to change the request to `self.client.get(uri)`, because in the docs there's a "GET" before the request URI - but then the auth didn't work anymore :(

Can you help me with what I have to change to tell the server that I don't want to write anything?

**Comment by black-roland** [comment]
@rexyiy Hi! Please try [`/beta/me/outlook/taskFolders`](https://docs.microsoft.com/en-us/graph/api/outlookuser-list-taskfolders?view=graph-rest-beta&tabs=http#request) with GET.

By the way, I've just implemented support for adding tasks to a specific list by `list_name`. You can find the implementation of the method to get folders [here](https://github.com/black-roland/homeassistant-microsoft-todo/commit/5e2171615c407da567c7808f93401f16f92a453c#diff-8aaa839e1cc8aaf6a51a1d0362e7f642R52) :wink:

**Comment by rexyiy** [comment]
Thank you, that helped! And the list_name implementation is great! 🥇
