### ISSUE TITLE
Use list_name without emojis

### ISSUE THREAD

**Issue by noxhirsch** [black-roland/homeassistant-microsoft-todo#13]
In MS ToDo you can add emojis to list names. If you want to add a task to such a list, you have to add it to `list_name`. This can look like this:
`🍔List Name`
or with more 'complex' emojis even like this:
`👨\u200d💼List Name` (it's this one:  👨‍💼)
Is it possible to ignore the emojis when filtering for the right list?

And another question which is not worth to open another issue, because I think I know the answer: Is it right that it is not possible to access "My Day" via the API at the moment?

**Comment by black-roland** [comment]
> Is it possible to ignore the emojis when filtering for the right list?

Technically yes but I'm not sure that I understand your use case :thinking: I've just checked and the integration works with emojis for me. Did you experience any issues with emojis?

If you would like to hide list names from the config I can suggest using [secrets](https://www.home-assistant.io/docs/configuration/secrets/).

> Is it right that it is not possible to access "My Day" via the API at the moment?

Good question. It seems "My Day" API isn't documented but for tracking let me add a task to investigate API. Thanks.

**Comment by noxhirsch** [comment]
`Technically yes but I'm not sure that I understand your use case 🤔 I've just checked and the integration works with emojis for me. Did you experience any issues with emojis?`

No, I didn't experience any real issues (and also don't want to hide them), but at first I didn't get that the emojis are part of the list name - especially in the Android app it looks like an extra setting and has nothing to do with the list name. The only benefit when filtering out the emojis is, that it's easier for beginner and that you don't have to search for the emojis in the emoji list, because you can't copy & paste them from the app. 
But a notice in the docs would also do the job ;)

**Comment by black-roland** [comment]
> especially in the Android app it looks like an extra setting and has nothing to do with the list name

Interesting, I didn't know that! There is no such option in the web app. Then it makes sense to fix this issue. Thanks.

**Comment by black-roland** [comment]
Fixed, now the integration should handle emoji icons correctly. Thanks!
