### ISSUE TITLE
Cannot authenticate | duckdns | native client suggestion

### ISSUE THREAD

**Issue by PaFcio** [black-roland/homeassistant-microsoft-todo#37]
Hi,

I have tried to configure this addon for few days now. When trying to configure it tries to authenticate via link including Raspberry local IP hence I receive error:

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

When I manually change uri to url and IP to my duckdns domain I am able to push it through to authorize on Azure side. It even returns to my HA instance but still it seems to not receive token hence following error:

Unable to create task: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/beta/me/outlook/tasks. Response: {'error': {'code': 'InvalidAuthenticationToken', 'message': 'Access token is empty.', 'innerError': {'date': '2020-10-14T19:30:02', 'request-id': 'some_id', 'client-request-id': 'id_same_as_the_other_one'}}}

Would it be able to incorporate alternative auth method similar to what following Office 365 addon uses? Authentication with this method was pretty straight forward there.

https://github.com/PTST/O365-HomeAssistant

**Comment by black-roland** [comment]
Sorry for the delay in replying. Could you please check if `access_token` property exists in the `.ms_todo_auth.json` file (in your Home Assistant directory)? Please also try removing `.ms_todo_auth.json` file and restart Home Assistant.

By the way, thanks for pointing to the O365-HomeAssistant component. Will take a look.

**Comment by PaFcio** [comment]
Hi, sorry it took me so long to reply as well. I did try to reinstall the addon, made sure that I follow all the instructions closely but all in all 1st post still applies. Though after reinstall and doing Azure side all over again there is a change in this point:

"When I manually change uri to url and IP to my duckdns domain I am able to push it through to authorize on Azure side. It even returns to my HA instance but still it seems to not receive token hence following error:"

I am able to return to HA instance this way but I do not receive an Microsoft window for confirming app access and authentication now. After changing "uri" to "url" and local IP to DNS address I just return to HA dashboard and that's all.

I have searched the HA folder for `.ms_todo_auth.json` but didn't find it anywhere (I understand it should be under /config right?).

**Comment by black-roland** [comment]
@PaFcio Could you please try updating to a new version? I hope this should solve issues with URLs.

> I have searched the HA folder for .ms_todo_auth.json but didn't find it anywhere (I understand it should be under /config right?).

The location depends on the home directory of a user which is used to run Home Assistant. For example, `/home/homeassistant/.homeassistant/.ms_todo_auth.json` or similar.

**Comment by PaFcio** [comment]
Hi, so I have updated to new version and tried to authorize again to no success. Started digging again:

- redirect URI seems to be ok now (it is based on my duckdns domain so ok)
- given above, it still gives me `invalid_request:` error. No idea why
- I have created fresh Azure App Registration looking for answers. Made sure to make redirect URI correct (https://domain:port/api/microsoft-todo)
- no success so I changed the link (the one from `Link Microsoft To Do account` in configuration notification) to have URL instead of URI. It passed me to authorization page (approved the access), it then pushes me to `https://domain:port/api/microsoft-todo?code=[code_here]` giving `500 Internal Server Error`
- I have tried with different platform (Mobile & Desktop instead of Web) because it has proper redirect prefix (https://login.live.com/oauth20_desktop.srf) but it results in `invalid_request:` as well and after changing URI to URL it sends me to url `https://login.live.com/oauth20_desktop.srf?code=[code_here]` - wrong move I guess

Given above 500 Int Server Error I suspect it might be connected to my http config. In configuration.yaml I have only those lines connected to that:

```
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```

My domain connection is configured via official DuckDNS addon.

Home Assistant manual mentions [APIs](https://www.home-assistant.io/integrations/http/#apis) but honestly I have no idea what to do with that :D

I sense that "`https://domain:port/api/microsoft-todo?code=[code_here]` giving `500 Internal Server Error`" is the key here.

I wonder if it would be possible to create `.ms_todo_auth.json` manually using authentication code?

Oh, and I have searched whole drive for `.ms_todo_auth.json` with no records found.

**Comment by PaFcio** [comment]
Hmm, you can disregard above. Somehow after restart and another try of authentication I got `Microsoft To Do has been successfully authorized! You can close this window now!`. Entities seem to be ok. Now I need to learn how to use it properly :D

Thanks a lot for your help and your time!

**Comment by black-roland** [comment]
I'm glad the issue was resolved :relaxed:
