### ISSUE TITLE
Token refresh issue

### ISSUE THREAD

**Issue by genem2** [black-roland/homeassistant-microsoft-todo#41]
This morning, HA reported my google calendar token expired, so I deleted that file and REauthenticated it into Calendar.
(Edit: Typo fix)

Now I'm receiving a similar error with microsoft_todo:

`2020-12-12 05:39:05 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up microsoft_todo platform for calendar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 
`

Ok, so I Uninstalled/Installed this from the store again, renaming-off my .ms_todo_auth.json and Clicked the button to configure Microsoft To Do.

That completes, sends what appears to be a proper callback URL to my server with:  /api/microsoft-todo?code=xxx&state=yyy

but then the browser shows:

500 Internal Server Error
Server got itself in trouble

The HA log then shows:

oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS90023: **_Public clients can't send a client secret_**.
Trace ID: 6caea922-afac-4668-a0bf-c1bdef539700
Correlation ID: 9914964d-2f74-4616-9ed6-5108dc91ff61

Related?
Anyone else?

Thanks.

My Config:
`System Health

Home Assistant Core Integration

version: 0.118.5
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.107-Unraid
arch: x86_64
timezone: America/Los_Angeles

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Lovelace

dashboards: 1
mode: storage
views: 6
resources: 18`

**Comment by genem2** [comment]
Argh... talk about a previous life.  I just noticed I went down this path earlier back on #15 

I checked my Azure Web redirect URL, and it's properly pointing to my domain URL. Still getting the 500, clicking the blue button that I should have been authenticated, but after a HA restart, I'm still not linked. This was working flawlessly for so long. Maybe it'll just start working again as it did back [here](https://github.com/black-roland/homeassistant-microsoft-todo/issues/15#issuecomment-565456501) in Update 2.

**Comment by genem2** [comment]
Yes, closed issue, but for future reference - perhaps even by me:
I gave up, but then looked at that configure*..microsoft_to_do entity.  I copied the https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=c....... URL from the attribute, pasted that into a separate browser window, and it worked:
_Microsoft To Do has been successfully authorized! You can close this window now!_
Clicked the blue-button back in the HA Notification, restarted HA, and all's good again.

**Comment by rasssta** [comment]
This should really be well documented as I've ran into this issue twice now...

@genem2 Perhaps re-open this issue?
