### ISSUE TITLE
Change Hass service domain to make it consistent with similar components

### ISSUE THREAD

**Issue by black-roland** [black-roland/homeassistant-microsoft-todo#5]
Change `microsoft_todo.ms_todo_new_task` to `calendar.microsoft_todo_new_task` similar to [Todoist component](https://www.home-assistant.io/integrations/todoist/#services).

**Comment by noxhirsch** [comment]
For your information: https://github.com/home-assistant/home-assistant/pull/29131
It's now `todoist.new_task` with upcoming HA version 103.0

**Comment by black-roland** [comment]
Great, will take a look. Thanks.
