### ISSUE TITLE
Display ToDos as list

### ISSUE THREAD

**Issue by Talvien** [black-roland/homeassistant-microsoft-todo#61]
I'm looking for a possibility to show the item entries of the to-do calendar in a simple list.
Didn't find one so far, any advice?

**Comment by ssmorris** [comment]
Might be worth trying [this simple card](https://github.com/ssmorris/lovelace-attribute-list-view).  I use it to show the overdue tasks attribute as a bulleted list, it can easily be pointed at the all_tasks attribute of a todo list also.

**Comment by black-roland** [comment]
@Talvien Please also take a look at #43.
