### ISSUE TITLE
Screenshot how it looks like 

### ISSUE THREAD

**Issue by vdbrink** [black-roland/homeassistant-microsoft-todo#66]
Can someone show me how this integration can look like in home assistant?
1. Can I see all the todo lists? 
2. Can I show just a single one? 
3. How does a finished tasked looked like? 

I'm looking how I can make a digital kitchen dashboard with multiple todo lists on it.

**Comment by black-roland** [comment]
This integration adds sensors for each to-do list that you can find on the developer tools page:

![2022-01-11_00-11](https://user-images.githubusercontent.com/1756198/148840124-ace78bcc-1e71-47aa-be29-25e408a52973.png)

But if you would like to show a list in Lovelace please refer to these comments: https://github.com/black-roland/homeassistant-microsoft-todo/issues/61#issuecomment-889161589 https://github.com/black-roland/homeassistant-microsoft-todo/issues/43#issuecomment-772077353

Hopefully this helps :slightly_smiling_face:

**Comment by black-roland** [comment]
I've also updated the README with some details, please take a look: https://github.com/black-roland/homeassistant-microsoft-todo#calendar-sensors

I'm going to close this issue but please don't hesitate to reopen if you have any questions.

**Comment by vdbrink** [comment]
Thanks!
