### ISSUE TITLE
2022.3.0: Requirements for microsoft_todo not found: ['emoji==0.6.1'].

### ISSUE THREAD

**Issue by genem2** [black-roland/homeassistant-microsoft-todo#75]
Heads up.  2022.3.0 update pops:

`Platform error calendar.microsoft_todo - Requirements for microsoft_todo not found: ['emoji==0.6.1'].`

After seeing this in the log, too:

```
2022-03-02 14:30:31 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package emoji==0.6.1: 
ERROR: Could not find a version that satisfies the requirement emoji==0.6.1 
(from versions: 0.1.0, 0.2, 0.2.1, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.8, 0.3.9, 0.4.0, 0.4.5, 
0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.6.0, 1.6.1, 1.6.3)
ERROR: No matching distribution found for emoji==0.6.1
```
I modified the manifest file to change 0.6.1 to 0.6.0, and it looks like it's working for now.
Not familiar with this; could this be something they missed in this new Core Docker container?

Tnx
## System Health

version | core-2022.3.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.28-Unraid
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4821
Installed Version | 1.23.0
Stage | running
Available Repositories | 1011
Downloaded Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 21
views | 8
mode | storage

</details>

**Comment by stroodle96** [comment]
Hello, @genem2 . I am having the same issue. How did you modify the manifest file to fix it?

**Comment by genem2** [comment]
I wouldn't call this a fix, but I did get around it temporarily by editing the manifest file to indicate a requirement of **_6.0_** rather than 6.1. (Then restart HA, obviously.)

.../custom_components/microsoft_todo/manifest.json

{
  "domain": "microsoft_todo",
  "name": "Microsoft To Do",
  "version": "1.0.5",
  "documentation": "https://github.com/black-roland/homeassistant-microsoft-todo",
  "dependencies": [],
  "codeowners": ["@black-roland"],
  "requirements": [
    "requests_oauthlib==1.3.0",
    "emoji==**_0.6.0_**"
  ]
}

**Comment by almostserious** [comment]
This dependency was last updated 10. Jan with release 1.0.5 to 0.6.1.
Emoji doesn't have a release 0.6.1 though. Maybe it was a typo and supposed to be the much newer 1.6.1

What I'm wondering: Why do we only see this error now with Homeassistant March update. I was just checking if emoji has been in previous versions of HA requirements but couldn't find it.

**Comment by umutcelebi** [comment]
> I wouldn't call this a fix, but I did get around it temporarily by editing the manifest file to indicate a requirement of **_6.0_** rather than 6.1. (Then restart HA, obviously.)
> 
> .../custom_components/microsoft_todo/manifest.json
> 
> {
>   "domain": "microsoft_todo",
>   "name": "Microsoft To Do",
>   "version": "1.0.5",
>   "documentation": "https://github.com/black-roland/homeassistant-microsoft-todo",
>   "dependencies": [],
>   "codeowners": ["@black-roland"],
>   "requirements": [
>     "requests_oauthlib==1.3.0",
>     "emoji==**_0.6.0_**"
>   ]
> }
> 

Thanks, this workaround worked for me!

**Comment by black-roland** [comment]
Thank you! Will be fixed in the next release.
