### ISSUE TITLE
2022.5. - CalendarEventDevice is deprecated

### ISSUE THREAD

**Issue by stroodle96** [black-roland/homeassistant-microsoft-todo#79]
After upgrading to HA version 2022.5, I am getting the warning below.  Not sure if this needs looked into or not. 

Logger: homeassistant.components.calendar
Source: components/calendar/__init__.py:197
Integration: Calendar (documentation, issues)
First occurred: 3:13:10 PM (1 occurrences)
Last logged: 3:13:10 PM

CalendarEventDevice is deprecated, modify MSToDoListDevice to extend CalendarEntity

**Comment by black-roland** [comment]
Thanks for reporting. Will be fixed in the next release.

**Comment by rasssta** [comment]
@black-roland When will the next release...be released?

**Comment by black-roland** [comment]
@rasssta Thank you for your patience, I wanted to verify it before releasing but didn't have a chance. v1.0.6 was released.
